name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "my-flask-app-pack"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha}}.zip"
  AWS_REGION_NAME           : "eu-central-1"
  MY_AWS_ACCESS_KEY         : ${{ secrets.MY_AWS_ACCESS_KEY }}
  MY_AWS_SECRET_KEY         : ${{ secrets.MY_AWS_SECRET_KEY }}
on:
  push:
   branches:
   - main
  
jobs:
    my_ci_part:
      runs-on: ubuntu-latest
      
      steps: 
      - name: Git clone our repo
        uses: actions/checkout@v1


      - name: Create ZIP 
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
  

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           role-session-name: GitHubActions
           aws-access-key-id: ${{ env.MY_AWS_ACCESS_KEY }} 
           aws-secret-access-key: ${{ env.MY_AWS_SECRET_KEY }}
           aws-region: ${{ env.AWS_REGION_NAME }}





      - name: Copy Deploymabt package to S3 bucket
        run : aws s3 cp  ${{ env.DEPLOY_PACKAGE_NAME }} s3://  ${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
        
      - name: Print Happy ci finich
        run : echo " CI PIPPELINE PART FINISH SUCESFULLY"
       
        
#end4
